dist: trusty
sudo: required

language: go

# This moves Kubernetes specific config files.
env:
- CHANGE_MINIKUBE_NONE_USER=true

before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
- sudo apt-get update -qq
- curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
# - sudo apt-get install -qq ansible

install:
# Make root mounted as rshared to fix kube-dns issues.
- sudo mount --make-rshared /
# Download kubectl, which is a requirement for using minikube.
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.10.4/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
# Download minikube.
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.28.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
# Run it
- sudo ./bin/start.sh
# Fix the kubectl context, as it's often stale.
- minikube update-context
# Wait for Kubernetes to be up and ready.
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
# Clone tester and testee
- git clone https://github.com/apache/incubator-openwhisk.git
- mkdir -p ../../projectodd
- git clone https://github.com/projectodd/kwsk.git ../../projectodd/kwsk
# Install and configure
- ./bin/install.sh
- cp whisk.properties incubator-openwhisk/
- perl -p -i -e "s:/home/jim/src:$PWD:" incubator-openwhisk/whisk.properties
- pushd ../../projectodd/kwsk && dep ensure && popd

before_script:
- go run ../../projectodd/kwsk/cmd/kwsk-server/main.go --port 8080 --istio $(minikube ip):32000 >kwsk.log 2>&1 &

script:
- pushd incubator-openwhisk
- ./gradlew :tests:test --tests "system.basic.WskRest*"
- popd

after_script:
- jobs
- kill %1

after_failure:
- echo "############# FAILURE #############"
- cat kwsk.log

